version: "3.8"
services:
  application:
    container_name: gestor_application
    build: ./
    ports:
      - 9011:80
    volumes:
      - ./:/usr/share/nginx/html
    restart: always
    networks:
      - docker
  mysql:
    container_name: gestor_db
    image: mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: gestorPedidosDb
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    networks:
      - docker

networks:
  docker:
    driver: bridge
